language: objective-c
cache: bundler
osx_image: xcode11

branches:
  only:
    - master
    - develop

git:
  depth: 3

before_install:
  - chmod a+x ./fastlane/*.sh
  - gem update bundler

script:
  - "./fastlane/fastlane.sh"

matrix:
  include:
    - env: CI_DEVICE='platform=iOS Simulator,name=iPhone 7,OS=13.0'
    - env: CI_DEVICE='iPhone 8 (13.0)'
    - env: CI_DEVICE='platform=iOS Simulator,name=iPhone X,OS=13.0'

after_success:
  - bash <(curl -s https://codecov.io/bash)